
raft:
  cluster:
    address:
      ip: 127.0.0.1
      port: 33221
  node:
    id: 1
    address:
      ip: 0.0.0.0
      port: 33225
    event:
      # millisecond
      timeout: 1000
    transport:
      # millisecond
      request_timeout: 1000
